### ISSUE TITLE
Feature request: Option to install certain Flatpaks systemwide

### ISSUE THREAD

**Issue by IverCoder** [ublue-os/yafti#170]
It would make sense to install certain apps systemwide. Example, the Clocks, Calendar, and Firefox browser, which is supposed to be used by all users on the system. Installing them is inefficient on bandwidth and storage as they have to be downloaded and stored separately on each user.

I'm thinking of something like:
```yaml
packages:
- Camera: org.gnome.Snapshot
    DefaultInstallScope: system
      Togglable: false
```
