### ISSUE TITLE
Feature requst: New yafti mode 'conditional'

### ISSUE THREAD

**Issue by RoyalOughtness** [ublue-os/yafti#179]
The current available yafti modes are:

```
class YaftiRunModes(str, Enum):
    changed = "run-on-change"
    ignore = "run-once"
    disable = "disabled"
```

I'm proposing a new mode called 'conditional' that takes a conditional as input so that yafti can run based on information about the system

The syntax could look something like this:

```
title: Welcome to uBlue
properties:
  mode: "conditional"
  condition:
    run: flatpak remotes --columns=name | grep fedora
```
