### ISSUE TITLE
Yafti ignores post commands

### ISSUE THREAD

**Issue by meisme-dev** [ublue-os/yafti#90]
Yafti seems to be not running any post commands.
Steps to reproduce:
1. Create a yafti.yml with 
```yml
actions:
  post:
  - run: cp file1 file2 (can be literally any command)
```
2. Observe nothing happen

Expected behaviour: 
As shown in the README.md, it is expected that the post commands get executed after yafti is done with everything else.

Additional info:
When running with --debug, there is no indication that anything is happening. No errors, but the command does not get executed.
