### ISSUE TITLE
Notes about `yafti.yml`

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/yafti#94]
`key: value`

Is it just me, or is the `yafti.yml` format kind of irregular?

1. The formatting of lists where the key of the item is just an arbitrary name

When declaring packages inside a group, the format is
```yml
packages:
- Display Name: org.package.Identifier
```
which is a list where the key of the item is used as the item's name, which is a pretty great design tbh.

Now, there are two other places where the key is used as the name of the item, the first one being declaring package groups.
The format is as follows. 
```yml
groups:
  Core:
       ...
  Gaming:
       ...
  Office:
       ...
```
The one difference from declaring packages is that, while this is _basically an arbitrary list_, it's _not a YAML list_,

The other place where the key is used as the name of the item is when declaring screens. The format is as follows
```yml
screens:
  first-screen:
    ...
    values:
      title: "That was pretty cool"
      ...
  applications:
    ...
    values:
      title: Package Installation
      ...
  final-screen:
    ...
    values:
      title: "All done"
      ...
```
Now you notice, that this is also a list of screens with arbitrary keys that is _not a YAML list_. Also, the arbitrary keys are not used as the screen's titles, but the actual title is declared elsewhere.

Below are two refactorings of the example config file that address these inconsistencies.

<details>
<summary>This version normalizes using keys as display names when the objects are inside lists</summary>

```yml
title: uBlue First Boot
properties:
  mode: "run-on-change"
  path: "~/.config/yafti-first-run"
actions:
  pre:
  - run: /full/path/to/bin --with --params
  - run: /another/command run
  - yafti.plugin.flatpak:
      install: org.gnome.Calculator
  post:
  - run: /run/these/commands --after --all --screens
screens:
  - "That was pretty cool":
      source: yafti.screen.title
      values:
        icon: "/path/to/icon"
        description: |
          Time to play overwatch
  - "Package Installation":
      source: yafti.screen.package
      values:
        show_terminal: true
        package_manager: yafti.plugin.flatpak
        groups:
          - Core:
             description: All the good stuff
             packages:
             - Calculator: org.gnome.Calculator
             - Firefox: org.mozilla.firefox
          - Gaming:
             description: GAMES GAMES GAMES
             packages:
             - Steam: com.valvesoftware.Steam
             - Games: org.gnome.Games
          - Office:
             description: All the work stuff
             packages:
             - LibreOffice: org.libreoffice.LibreOffice
             - Calendar: org.gnome.Calendar
  - "All done!":
      source: yafti.screen.title
      values:
        icon: "/path/to/icon"
        description: |
          Thanks for installing, join the community, next steps
```

</details>

<details>
<summary>This version does not use any arbitrary keys</summary>

```yml
title: uBlue First Boot
properties:
  mode: "run-on-change"
  path: "~/.config/yafti-first-run"
actions:
  pre:
  - run: /full/path/to/bin --with --params
  - run: /another/command run
  - yafti.plugin.flatpak:
      install: org.gnome.Calculator
  post:
  - run: /run/these/commands --after --all --screens
screens:
  - source: yafti.screen.title
    values:
      title: "That was pretty cool"
      icon: "/path/to/icon"
      description: |
        Time to play overwatch
  - source: yafti.screen.package
    values:
      title: Package Installation
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      groups:
        - title: Core
          description: All the good stuff
          packages:
          - name: Calculator
            id: org.gnome.Calculator
          - name: Firefox
            id: org.mozilla.firefox
        - title: Gaming
          description: GAMES GAMES GAMES
          packages:
          - name: Steam
            id: com.valvesoftware.Steam
          - name: Games
            id: org.gnome.Games
        - title: Office:
          description: All the work stuff
          packages:
          - name: LibreOffice
            id: org.libreoffice.LibreOffice
          - name: Calendar
            id: org.gnome.Calendar
  - source: yafti.screen.title
    values:
      title: "All done"
      icon: "/path/to/icon"
      description: |
        Thanks for installing, join the community, next steps
```

</details>

2. The usage of `yafti.abc.xyz`

All the `source:` values in the screens start with `yafti.screen`. I assume that it's not an immediate concern to support screens in yafti that are not `screen`s or from `yafti`, so I'm wondering why not just have the value be an enum of strings, not IDs.

What baffles me more is in the action sections, the full ID of the flatpak "plugin" is used `yafti.plugins.flatpak`, while the run "plugin" is just called using `run`, when the files [are right next to each other ](https://github.com/ublue-os/yafti/blob/main/yafti/plugin/). As the [run.py](https://github.com/ublue-os/yafti/blob/main/yafti/plugin/run.py) inline docs state, it is possible to use it with either the short form `run` or the long form `yafti.plugins.run`, which makes me wonder why `yafti.plugins.flatpak` does not get the same sort of special treatment.

What this makes me feel like is that the yafti configuration is trying to be a DSL for creating tour-style apps.

---

Sorry about questioning your design choices, but I do think that we're still early enough to make breaking changes to the config file, while the uBlue org happens to be in control of all projects that use `yafti`.

**Comment by marcoceppi** [comment]
> 1. The formatting of lists where the key of the item is just an arbitrary name
> 
> The other place where the key is used as the name of the item is when declaring screens. The format is as follows
> 
> ```yaml
> screens:
>   first-screen:
>     ...
>     values:
>       title: "That was pretty cool"
>       ...
>   applications:
>     ...
>     values:
>       title: Package Installation
>       ...
>   final-screen:
>     ...
>     values:
>       title: "All done"
>       ...
> ```
> 

This is to allow for layering of config files. If you use lists here you're not able to extend a base config as there's no explicit reference to the key for the screen.

Given a base file:

```yaml
screens:
  first-screen:
    ...
    values:
      title: "That was pretty cool"
      ...
  applications:
    ...
    values:
      title: Package Installation
      ...
  final-screen:
    ...
    values:
      title: "All done"
      ...
```

there may be a supplemental file provided to the installer (not supported today, but was planned in the initial design:

```yaml
screens:
  applications:
    values:
      title: "Hello World"
```

If you layer this fragment on top of the previous you'll get:

```yaml
screens:
  first-screen:
    ...
    values:
      title: "That was pretty cool"
      ...
  applications:
    ...
    values:
      title: "Hello World"
      ...
  final-screen:
    ...
    values:
      title: "All done"
      ...
```

This would be either `yafti [BASE_CONFIG] [SUPPLEMENTAL_CONFIG ...]` or via `/etc/yafti.yml` then any `/etc/yafti.[a-z0-9].yml` loaded in lexicographic order.

List elements for keys don't give a lot of flexibility for this as you can't "overwrite" as there is no unique key. I decided to a point that extension wasn't as valuable and you see the switch to software titles as lists later into the spec. This is one of the limitations we had with firstboot and why I chose this pattern in particular.

While it hasn't panned out this way, early one we intended to ship a very slim `yafti.yml` in the main images. Downstream distros could then layer on a few overrides instead of copying the yaml config outright which would overwrite subsequent updates to the base yaml.

There are some suggestions I think we could adopt here but I'm resistant to removing top level screen keys to a list as it'll make composition and manipulation a lot harder in the future.

> 2. The usage of `yafti.abc.xyz`
> 
> All the `source:` values in the screens start with `yafti.screen`. I assume that it's not an immediate concern to support screens in yafti that are not `screen`s or from `yafti`, so I'm wondering why not just have the value be an enum of strings, not IDs.
> 
> What baffles me more is in the action sections, the full ID of the flatpak "plugin" is used `yafti.plugins.flatpak`, while the run "plugin" is just called using `run`, when the files [are right next to each other ](https://github.com/ublue-os/yafti/blob/main/yafti/plugin/?rgh-link-date=2023-05-01T16%3A46%3A12Z). As the [run.py](https://github.com/ublue-os/yafti/blob/main/yafti/plugin/run.py?rgh-link-date=2023-05-01T16%3A46%3A12Z) inline docs state, it is possible to use it with either the short form `run` or the long form `yafti.plugins.run`, which makes me wonder why `yafti.plugins.flatpak` does not get the same sort of special treatment.
> 

My intention is that `yafti.core` only ships the run plugin. All other plugins are supplementary / optional based on use case. For that reason I made `run` easy to use / type and implicitly run if you have something like

```yaml
 actions:
  pre:
  - /full/path/to/bin --with --params
```

Where an action / line without a plugin is implicitly interpreted as `yafti.plugins.run`. Plugins, and to an extent screens, are meant to be independent and extensible. The flatpak plugin is packaged with yafti for simplicity but over time as this project grows it'll likely move out of tree and especially out of core. Any repo can add a new yafti plugin [by adding this line to their `pyproject.toml`](https://github.com/ublue-os/yafti/blob/main/pyproject.toml#L29-L30)

> Sorry about questioning your design choices, but I do think that we're still early enough to make breaking changes to the config file, while the uBlue org happens to be in control of all projects that use `yafti`.

Yafti config is explicitly versioned - even though it's not included in `yafti.yaml` anytime a breaking change is introduced a new `version` top level key will be added. If no key is supplied it's assumed version 1 and I intend to support multiple configuration version formats for some time.

---

I'm not opposed to making changes. There's a lot to unpack in this issue, hopefully this helps shed some light on future plans that maybe weren't obvious and reasons on why some design choices were made.
